# -*- coding: utf-8 -*-
"""LLM-Agents_Tools.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1beAX53X0aDQDN7s67As36r7UBUjXDiPr
"""

!pip install -q transformers einops accelerate bitsandbytes
!pip install -q langchain langchain_community langchain-huggingface langchainhub langchain_chroma

!pip install wikipedia



from langchain_core.tools import Tool
from langchain.tools import WikipediaQueryRun, BaseTool
from langchain_community.utilities import WikipediaAPIWrapper

wikipedia = WikipediaQueryRun(api_wrapper=WikipediaAPIWrapper(to_k_results=1,doc_content_chars_max=3000))

print(wikipedia.run("Machine Learning"))

wikipedia_tool = Tool(name="wikipedia", description="You must never search for multiple concepts at a single step, you need to search one at a time. When asked to compare two concepts for example, search for each one individually.", func=wikipedia.run)

def current_day(*args, **kwargs):
  from datetime import date
  dia = date.today()
  dia = dia.srtftime('%d/%m/%Y')
  return dia

date_tool = Tool(name='Day', func = current_day, description="Use when you need to know the current date")

tools = (wikipedia_tool, date_tool)

"""React"""

import os
import getpass
os.environ["LANGCHAIN_API_KEY"] = getpass.getpass()

from langchain import hub
prompt = hub.pull("hwchase17/react")

"""LLM"""

from langchain_community.llms import HuggingFaceEndpoint
from langchain_community.chat_models.huggingface import ChatHuggingFace

llm = HuggingFaceEndpoint(repo_id="meta-llama/Meta-Llama-3-8B-Instruct", temperature=0.1)

from langchain.agents import AgentsExecutor, create_react_agent
agent = create_react_agent(llm=llm, tools=tools, prompt=prompt)

agent_executor = AgentsExecutor.from_agent_and_tools(agent=agent, tools=tools, verbose=True, handling_parsing_errors=True)



ans = agent_executor.run("input": "What day is it today?")

